@startuml stateDiagram

skinparam ClassAttributeIconSize 0
hide empty description

state OFF
state ON
state SLEEPING

[*] --> OFF

OFF --> OFF : off_button_pushed
OFF --> ON : on_button_pushed

ON --> OFF : off_button_pushed
ON --> SLEEPING : on_button_pushed

SLEEPING --> ON : on_button_pushed
SLEEPING --> OFF : off_button_pushed
@enduml
